name: CI/CD for React Native

on:
  push:
    branches:
      - automation-ios
  pull_request:
    branches:
      - automation-ios

jobs:
  ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Set up Ruby and CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS Release IPA
        run: |
          cd ios
          xcodebuild -workspace Automation.xcworkspace \
            -scheme Automation \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $PWD/build/Automation.xcarchive \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            -allowProvisioningUpdates

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath $PWD/build/Automation.xcarchive \
            -exportOptionsPlist $PWD/exportOptions.plist \
            -exportPath $PWD/build \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER=""

      - name: Upload iOS IPA as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-release.ipa
          path: ios/build/Automation.ipa
